version: '3.1'

services:
  zoo1:
    image: renci/zookeeper:3.4.11
    build:
      context: ./3.4.11
      dockerfile: Dockerfile
    container_name: zoo1
    restart: always
    hostname: zoo1
    networks:
      - zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    image: renci/zookeeper:3.4.11
    build:
      context: ./3.4.11
      dockerfile: Dockerfile
    container_name: zoo2
    restart: always
    hostname: zoo2
    networks:
      - zookeeper
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    image: renci/zookeeper:3.4.11
    build:
      context: ./3.4.11
      dockerfile: Dockerfile
    container_name: zoo3
    restart: always
    hostname: zoo3
    networks:
      - zookeeper
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888

networks:
  zookeeper:
